server:
  port: 8091

spring:
  config:
    import: optional:configserver:http://13.202.64.234:8085
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_7mS1HHaf23qpdUGakxf@mysql-3823015a-hussainsadik194-0e47.i.aivencloud.com:15876/algo-nexus-courseService?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_7mS1HHaf23qpdUGakxf
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: COURSE-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

